### ISSUE TITLE
Weapon speed hilariously high

### ISSUE THREAD

**Issue by ReturnToReason** [thehajo/LSBaka#2]
Upon finishing the intro my weapon speed is set to 1.84 prior to this it is set to 0.84 once mod configuration is finished. It appears as if when going through the intro or entering outside specifically my weapon speed gets a +1 added to it causing an extremely fast swing speed for any weapon.

Attempted fixes:
True armor disabling of weapon speed changes did not help when done before the +1 to weapon speed or after the +1

Found fixes:
Disabling Engarde appears to remove the extra point of weapon speed.

**Comment by thehajo** [comment]
Fixed in Version 1.3.3.1
