### ISSUE TITLE
Missing water near Dragon Bridge

### ISSUE THREAD

**Issue by Shurlikan** [thehajo/LSBaka#3]
![The Elder Scrolls V Skyrim Special Edition_2022 08 23-23 16](https://user-images.githubusercontent.com/19482151/186267417-8f6dd599-aaaa-4831-bb80-116512ffdd08.png)
![The Elder Scrolls V Skyrim Special Edition_2022 08 23-23 16_1](https://user-images.githubusercontent.com/19482151/186267624-441039b4-18f9-417e-8fc0-817399248207.png)

**Comment by thehajo** [comment]
Thought i had this pinned... anyway it's pinned now in the discod channel. Change the load order so that DynDOLOD.esm loads after RelicsofHyrleDragonborn.esp. There is a screenshot in the discord channel.
